### ISSUE TITLE
UmbracoRegularExpression not working as expected

### ISSUE THREAD

**Issue by GianniDPC** [rasmuseeg/Our.Umbraco.DataAnnotations#5]
If I use the "UmbracoRegularExpression" data annotation attribute it always defaults to the default MVC error for this validation, even when I use the ResourceName property.

The expected outcome would be for the validationmessage to display the value that has been set on the key in the Umbraco dictionary.

Other annotations like UmbracoRequired and UmbracoDisplayName work fine even with the ResourceName property set.

Example:

```
        [UmbracoRequired]
        [UmbracoRegularExpression(@"^(?:\+\d{2,15})*", ResourceName = "test")]
        public string Phone { get; set; }
```
Did I forget an extra step to get this working or is this a bug? I'm using Umbraco version 7.13.2

**Comment by rasmuseeg** [comment]
I think this is a bug, I'll have to take a closer look. :-)

**Comment by rasmuseeg** [comment]
This is now merged, but with changes, and updated readme.md

**Comment by GianniDPC** [comment]
Thank you!
